import dao.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author samuel.toledo
 */
public class Login_page extends javax.swing.JFrame /* mostra que é uma página do swing*/{
    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents(); /* inicializa os componentes da GUI*/
        setLocationRelativeTo(null); // faz a janela ser aberta no centro na tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        i_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_fechar = new javax.swing.JButton();
        i_senha = new javax.swing.JTextField();
        b_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de estoque");
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem-Vindo!");

        jLabel2.setText("E-mail:");

        i_email.setToolTipText("fulano@seudomínio.com");
        i_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_emailActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        b_fechar.setText("Fechar");
        b_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fecharActionPerformed(evt);
            }
        });

        i_senha.setToolTipText("******************");
        i_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_senhaActionPerformed(evt);
            }
        });

        b_login.setText("Fazer log-in");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(i_email, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(i_senha, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(b_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(i_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(i_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_fechar)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_emailActionPerformed

    private void i_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_senhaActionPerformed

    private void b_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fecharActionPerformed
    // Quando apertar o botão de sair
    int a = JOptionPane.showConfirmDialog(null, "Têm certeza que você quer fechar o aplicativo?", "Select",JOptionPane.YES_NO_OPTION); //mostra uma janela de texto perguntando se quer sair mesmo
    if (a == 0) /* se a opção for sim, fecha o aplicativo*/{
        System.exit(0); // fechar o aplicativo
    }
    }//GEN-LAST:event_b_fecharActionPerformed

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // Botão de log in é apertado
        String email = i_email.getText(); // transforma o email num valor de texto(string)
        String senha = i_senha.getText(); // transforma a senha num valor de texto(string)
        
        int temp = 0; // cria uma variável temporária(chamei de temp para lembrar que é temporária, mas pode ser chamada de qualquer coisa)
        
        try {
            Connection con = ConnectionProvider.getCon(); // seta uma variável de tipo conexão(Connection) usando a classe ConnectionProvider, que tem o método getCon, que pega a conexão
            Statement st = con.createStatement(); // cria um client pra database no código, podendo receber código que interage com o SQL
            ResultSet rs = st.executeQuery("select *from appuser where email ='"+email+"' and password='"+senha+"' and status='Ativo'"); // cria uma variável do tipo ResultSet(Grupo de respostas) para armazenar a pesquisa por um usuário e, usando a classe st(que faz possível o envio de comandos para o SQL), pesquisa na database por um usuário com os dados inseridos e se o mesmo é ativo
            while(rs.next()) { // loop que procura por um usuário com as mesmas informações nos próximos resultados de pesquisa e retorna um verdadeiro se encontrar algo. Continua procurando até o fim da lista se não achar nada
                temp = 1; // quando o loop encontra algo, transforma a temp em 1 para parar
                setVisible(false); // esconde a página quando acha um login válido
                new Home(rs.getString("userRole")).setVisible(true); // mostra a página início(Home)
            }
            if (temp == 0) {
                JOptionPane.showMessageDialog(null, "Email ou senha incorretos."); // mostra a notificação de erro quando não achar nenhum login com as informações inseridas
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_b_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_fechar;
    private javax.swing.JButton b_login;
    private javax.swing.JTextField i_email;
    private javax.swing.JTextField i_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
