
import java.sql.*;
import dao.ConnectionProvider;
import java.lang.reflect.AccessFlag;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author samuel.toledo
 */
public class ManageProducts extends javax.swing.JFrame {

    private int productPK = 0;
    private int totalQuantity = 0;

    /**
     * Creates new form ManageProducts
     */
    public ManageProducts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void getAllCategories() {
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from category");
            dd_cat.removeAllItems();
            while (rs.next()) {
                dd_cat.addItem(rs.getString("category_pk") + "-" + rs.getString("name"));
            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private boolean validateFields(String formType) {
        if (formType.equals("edit") && !i_nome.getText().equals("") && !i_desc.getText().equals("") && !i_preço.getText().equals("")) {
            return false;
        } else if (formType.equals("new") && !i_nome.getText().equals("") && !i_desc.getText().equals("") && !i_qnt.getText().equals("") && !i_preço.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_produtos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        i_qnt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        i_nome = new javax.swing.JTextField();
        lbl_qnt = new javax.swing.JLabel();
        i_preço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        i_desc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dd_cat = new javax.swing.JComboBox<>();
        b_salvar = new javax.swing.JButton();
        b_atualizar = new javax.swing.JButton();
        b_resetare = new javax.swing.JButton();
        b_sair = new javax.swing.JButton();
        b_gcat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Gerenciar produtos");

        tb_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Descrição", "ID da categoria", "Categoria", "Preço"
            }
        ));
        tb_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_produtos);

        jLabel2.setText("Nome");

        i_qnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_qntActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço");

        i_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_nomeActionPerformed(evt);
            }
        });

        lbl_qnt.setText("Quantidade");

        i_preço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_preçoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        i_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_descActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoria");

        dd_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        b_salvar.setText("Salvar");
        b_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salvarActionPerformed(evt);
            }
        });

        b_atualizar.setText("Atualizar");
        b_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atualizarActionPerformed(evt);
            }
        });

        b_resetare.setText("Resetar");
        b_resetare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetareActionPerformed(evt);
            }
        });

        b_sair.setText("Sair");
        b_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sairActionPerformed(evt);
            }
        });

        b_gcat.setText("Gerenciar categorias");
        b_gcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gcatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_preço)
                            .addComponent(i_nome)
                            .addComponent(i_qnt)
                            .addComponent(i_desc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dd_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_gcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_qnt)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(b_salvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(b_atualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(b_resetare)
                                        .addGap(27, 27, 27)
                                        .addComponent(b_sair)))
                                .addGap(0, 33, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_qnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_preço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_gcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dd_cat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_salvar)
                            .addComponent(b_atualizar)
                            .addComponent(b_resetare)
                            .addComponent(b_sair))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        setLocationRelativeTo(null);
        getAllCategories();
        DefaultTableModel model = (DefaultTableModel) tb_produtos.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product inner join category on product.category_fk = category.category_pk");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("product_pk"), rs.getString("name"), rs.getString("quantity"), rs.getString("description"), rs.getString("category_fk"), rs.getString(8), rs.getString("price")});
            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        b_atualizar.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void i_qntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_qntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_qntActionPerformed

    private void i_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_nomeActionPerformed

    private void i_preçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_preçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_preçoActionPerformed

    private void i_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_descActionPerformed

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_b_sairActionPerformed

    private void b_resetareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetareActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageProducts().setVisible(true);
    }//GEN-LAST:event_b_resetareActionPerformed

    private void b_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salvarActionPerformed
        // TODO add your handling code here:
        String name = i_nome.getText();
        String quantity = i_qnt.getText();
        String description = i_desc.getText();
        String price = i_preço.getText();
        String category = (String) dd_cat.getSelectedItem();
        String categoryId[] = category.split("-", 0);
        if (validateFields("new")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são necessários.");
        } else {
            try {
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into product(name,quantity,price,description,category_fk) values(?,?,?,?,?)");
                ps.setString(1, name);
                ps.setString(2, quantity);
                ps.setString(3, price);
                ps.setString(4, description);
                ps.setString(5, categoryId[0]);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso.");
                setVisible(false);
                new ManageProducts().setVisible(true);
                con.close();
                ps.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_b_salvarActionPerformed

    private void tb_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtosMouseClicked
        // TODO add your handling code here:
        int index = tb_produtos.getSelectedRow();
        TableModel model = tb_produtos.getModel();

        String id = model.getValueAt(index, 0).toString();
        productPK = Integer.parseInt(id);

        String nome = model.getValueAt(index, 1).toString();
        i_nome.setText(nome);

        String quantidade = model.getValueAt(index, 2).toString();
        totalQuantity = 0;
        lbl_qnt.setText("Adicionar quantidade");
        i_qnt.setText(quantidade);
        totalQuantity = Integer.parseInt(quantidade);

        String preço = model.getValueAt(index, 6).toString();
        i_preço.setText(preço);

        String descrição = model.getValueAt(index, 3).toString();
        i_desc.setText(descrição);

        dd_cat.removeAllItems();
        String categoryId = model.getValueAt(index, 4).toString();
        String categoryName = model.getValueAt(index, 5).toString();
        dd_cat.addItem(categoryId + "-" + categoryName);

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from category");
            while (rs.next()) {
                if (Integer.parseInt(categoryId) != rs.getInt(1)) {

                }
                dd_cat.addItem(rs.getString("category_pk") + "-" + rs.getString("name"));

            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        b_salvar.setEnabled(false);
        b_atualizar.setEnabled(true);
    }//GEN-LAST:event_tb_produtosMouseClicked

    private void b_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atualizarActionPerformed
        // TODO add your handling code here:
        String name = i_nome.getText();
        String quantity = i_qnt.getText();
        String description = i_desc.getText();
        String price = i_preço.getText();
        String category = (String) dd_cat.getSelectedItem();
        String categoryId[] = category.split("-", 0);
        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são necessários.");
        } else {
            try {
                if (!quantity.equals("")) {
                    totalQuantity = totalQuantity + Integer.parseInt(quantity);
                }
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("update product set name=?, quantity=?, price=?, description=?, category_fk=? where product_pk=?");
                ps.setString(1, name);
                ps.setInt(2, totalQuantity);
                ps.setString(3, price);
                ps.setString(4, description);
                ps.setString(5, categoryId[0]);
                ps.setInt(6, productPK);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso.");
                setVisible(false);
                new ManageProducts().setVisible(true);
                con.close();
                ps.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_b_atualizarActionPerformed

    private void b_gcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gcatActionPerformed
        // TODO add your handling code here:
        new ManageCathegories().setVisible(true);
    }//GEN-LAST:event_b_gcatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_atualizar;
    private javax.swing.JButton b_gcat;
    private javax.swing.JButton b_resetare;
    private javax.swing.JButton b_sair;
    private javax.swing.JButton b_salvar;
    private javax.swing.JComboBox<String> dd_cat;
    private javax.swing.JTextField i_desc;
    private javax.swing.JTextField i_nome;
    private javax.swing.JTextField i_preço;
    private javax.swing.JTextField i_qnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_qnt;
    private javax.swing.JTable tb_produtos;
    // End of variables declaration//GEN-END:variables
}
