
import java.sql.*;
import java.sql.Statement;
import javax.swing.*;
import dao.ConnectionProvider;
import java.awt.Color;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author samuel.toledo
 */
public class ManageOrder extends javax.swing.JFrame {

    private int clientPK = 0;
    private int productPK = 0;
    private int finaltotal = 0;
    private boolean checa = false;
    private int salePK = 0;

    /**
     * Creates new form ManageOrder
     */
    public ManageOrder() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        i_pprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_carrinho = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_clientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_products = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        i_products = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        i_cemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        i_ctelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        i_cnome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        b_salvar = new javax.swing.JButton();
        b_reset = new javax.swing.JButton();
        b_sair = new javax.swing.JButton();
        b_addcart = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_cn = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        i_pqnt1 = new javax.swing.JTextField();
        i_pprice1 = new javax.swing.JTextField();
        i_data = new javax.swing.JTextField();

        i_pprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_ppriceActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Registrar vendas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 30, -1, 52));

        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 102, -1, -1));

        tb_carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço", "SUBTOTAL"
            }
        ));
        tb_carrinho.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tb_carrinhoComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tb_carrinho);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 156, 312, 279));

        jLabel3.setText("Produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        tb_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Email"
            }
        ));
        tb_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_clientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 156, 288, 279));

        jLabel4.setText("Carrinho");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 102, -1, -1));

        tb_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Descrição", "ID categoria", "Categoria", "Preço"
            }
        ));
        tb_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_productsMouseClicked(evt);
            }
        });
        tb_products.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tb_productsComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(tb_products);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 156, 517, 279));

        jLabel5.setText("Cliente selecionado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 441, -1, -1));

        i_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_productsActionPerformed(evt);
            }
        });
        getContentPane().add(i_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 463, 517, -1));

        jLabel6.setText("Telefone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 491, -1, -1));

        i_cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_cemailActionPerformed(evt);
            }
        });
        getContentPane().add(i_cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 563, 288, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 541, -1, -1));

        i_ctelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_ctelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(i_ctelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 513, 288, -1));

        jLabel8.setText("Produto selecionado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 441, -1, -1));

        i_cnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_cnomeActionPerformed(evt);
            }
        });
        getContentPane().add(i_cnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 463, 288, -1));

        jLabel9.setText("Preço");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 491, -1, -1));

        jLabel10.setText("Quantidade vendida");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 541, -1, -1));

        b_salvar.setText("Salvar venda");
        b_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(b_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 312, -1));

        b_reset.setText("Resetar");
        b_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetActionPerformed(evt);
            }
        });
        getContentPane().add(b_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 570, 312, -1));

        b_sair.setText("Sair");
        b_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sairActionPerformed(evt);
            }
        });
        getContentPane().add(b_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 312, -1));

        b_addcart.setText("Adicionar ao carrinho");
        b_addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addcartActionPerformed(evt);
            }
        });
        getContentPane().add(b_addcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 636, -1, -1));

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_total.setText("00000");
        lbl_total.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lbl_totalComponentShown(evt);
            }
        });
        getContentPane().add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 441, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("TOTAL:  R$");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 441, -1, -1));

        cb_cn.setText("Cliente novo");
        cb_cn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_cnMouseClicked(evt);
            }
        });
        cb_cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cnActionPerformed(evt);
            }
        });
        getContentPane().add(cb_cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 600, -1, -1));

        jLabel11.setText("Data");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 491, -1, -1));

        i_pqnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_pqnt1ActionPerformed(evt);
            }
        });
        getContentPane().add(i_pqnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 563, 517, -1));

        i_pprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_pprice1ActionPerformed(evt);
            }
        });
        getContentPane().add(i_pprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 517, -1));

        i_data.setToolTipText("dd/mm/aaaa");
        i_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_dataActionPerformed(evt);
            }
        });
        getContentPane().add(i_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 510, 312, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_productsActionPerformed

    private void i_cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_cemailActionPerformed

    private void i_ctelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_ctelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_ctelefoneActionPerformed

    private void i_cnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_cnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_cnomeActionPerformed

    private void i_ppriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_ppriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_ppriceActionPerformed

    private void b_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageOrder().setVisible(true);
    }//GEN-LAST:event_b_resetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // esconde o aviso

        DefaultTableModel model3 = (DefaultTableModel) tb_carrinho.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement st = con.prepareStatement("select *from sale_product where sale_fk = ?");
            st.setInt(1, salePK);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                model3.addRow(new Object[]{rs.getString("name"), rs.getString("quantity"), rs.getString("price"), rs.getString("subtotal")});
            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // tabela de clientes
        DefaultTableModel model1 = (DefaultTableModel) tb_clientes.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from client");
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString("client_pk"), rs.getString("name"), rs.getString("mobileNumber"), rs.getString("email")});
            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // tabela de produtos
        DefaultTableModel model2 = (DefaultTableModel) tb_products.getModel();
        try {
            Connection con2 = ConnectionProvider.getCon();
            Statement st2 = con2.createStatement();
            ResultSet rs2 = st2.executeQuery("select *from product inner join category on product.category_fk = category.category_pk");
            while (rs2.next()) {
                model2.addRow(new Object[]{rs2.getString("product_pk"), rs2.getString("name"), rs2.getString("quantity"), rs2.getString("description"), rs2.getString("category_fk"), rs2.getString(8), rs2.getString("price")});
            }
            con2.close();
            st2.close();
            rs2.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_b_sairActionPerformed

    private void cb_cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_cnActionPerformed

    private void tb_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clientesMouseClicked
        // tabela de clientes
        int indexclient = tb_clientes.getSelectedRow();
        TableModel model = tb_clientes.getModel();

        String id = model.getValueAt(indexclient, 0).toString();
        clientPK = Integer.parseInt(id);

        String nome = model.getValueAt(indexclient, 1).toString();
        i_cnome.setText(nome);

        String telefone = model.getValueAt(indexclient, 2).toString();
        i_ctelefone.setText(telefone);

        String email = model.getValueAt(indexclient, 3).toString();
        i_cemail.setText(email);
    }//GEN-LAST:event_tb_clientesMouseClicked

    private void tb_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_productsMouseClicked
        // TODO add your handling code here:
        int indexprodutos = tb_products.getSelectedRow();
        TableModel model = tb_products.getModel();

        String id = model.getValueAt(indexprodutos, 0).toString();
        productPK = Integer.parseInt(id);

        String nome = model.getValueAt(indexprodutos, 1).toString();
        i_products.setText(nome);

        String preço = model.getValueAt(indexprodutos, 6).toString();
        i_pprice1.setText(preço);
    }//GEN-LAST:event_tb_productsMouseClicked

    private void b_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salvarActionPerformed
        // TODO add your handling code here:
        String nome = i_cnome.getText();
        String telefone = i_ctelefone.getText();
        String email = i_cemail.getText();
        String vdata = i_data.getText();

        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into sale(client, total, data) values (?,?,?)");
            ps.setString(1, nome);
            ps.setInt(2, finaltotal);
            ps.setString(3, vdata);
            ps.executeUpdate();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from sale order by sale_pk desc limit 1");
            rs.next();
            salePK = rs.getInt("sale_pk");
            PreparedStatement ps1 = con.prepareStatement("update sale_product set sale_fk = ? where sale_fk = 0");
            ps1.setInt(1, salePK);
            ps1.executeUpdate();
            con.close();
            ps.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // checa para criar um cliente novo
        if (checa == true) {
            try {
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into client (name,mobileNumber,email) values(?,?,?)");
                ps.setString(1, nome);
                ps.setString(2, telefone);
                ps.setString(3, email);
                ps.executeUpdate();
                con.close();
                ps.close();
                setVisible(false);
                new ManageOrder().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (checa == false) {

            setVisible(false);
            new ManageOrder().setVisible(true);
        }
    }//GEN-LAST:event_b_salvarActionPerformed

    private void cb_cnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_cnMouseClicked
        // TODO add your handling code here:
        boolean isclicked = true;
        if (isclicked == true && checa == false) {
            checa = true;
        } else if (isclicked == true && checa == true) {
            checa = false;
        }
    }//GEN-LAST:event_cb_cnMouseClicked

    private void b_addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addcartActionPerformed
        // coloca o produto no carrinho
        String pname = i_products.getText();
        Integer pquantidade = Integer.parseInt(i_pqnt1.getText());
        Integer pprice = Integer.parseInt(i_pprice1.getText());
        Integer subtotal = pquantidade * pprice;
        Integer defaultsalefk = 0;

        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into sale_product(name, quantity, price, subtotal, sale_fk) values (?,?,?,?,?)");
            ps.setString(1, pname);
            ps.setInt(2, pquantidade);
            ps.setInt(3, pprice);
            ps.setString(4, subtotal.toString());
            ps.setInt(5, 0);
            ps.executeUpdate();
            con.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        tb_carrinho.setVisible(false);
        tb_carrinho.setVisible(true);

        lbl_total.setVisible(false);
        lbl_total.setVisible(true);

        tb_products.setVisible(false);
        tb_products.setVisible(true);

        finaltotal = finaltotal + subtotal;
    }//GEN-LAST:event_b_addcartActionPerformed

    private void lbl_totalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbl_totalComponentShown
        // TODO add your handling code here:
        lbl_total.setText(String.valueOf(finaltotal));
    }//GEN-LAST:event_lbl_totalComponentShown

    private void i_pqnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_pqnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_pqnt1ActionPerformed

    private void tb_productsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tb_productsComponentShown
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) tb_products.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select *from product inner join category on product.category_fk = category.category_pk");
            while (rs2.next()) {
                model2.addRow(new Object[]{rs2.getString("product_pk"), rs2.getString("name"), rs2.getString("quantity"), rs2.getString("description"), rs2.getString("category_fk"), rs2.getString(8), rs2.getString("price")});
            }
            con.close();
            rs2.close();
            st2.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tb_productsComponentShown

    private void tb_carrinhoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tb_carrinhoComponentShown
        // TODO add your handling code here:
        DefaultTableModel model3 = (DefaultTableModel) tb_carrinho.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement st = con.prepareStatement("select *from sale_product where sale_fk = ?");
            st.setInt(1, salePK);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                model3.addRow(new Object[]{rs.getString("name"), rs.getString("quantity"), rs.getString("price"), rs.getString("subtotal")});
            }
            con.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tb_carrinhoComponentShown

    private void i_pprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_pprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_pprice1ActionPerformed

    private void i_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_addcart;
    private javax.swing.JButton b_reset;
    private javax.swing.JButton b_sair;
    private javax.swing.JButton b_salvar;
    private javax.swing.JCheckBox cb_cn;
    private javax.swing.JTextField i_cemail;
    private javax.swing.JTextField i_cnome;
    private javax.swing.JTextField i_ctelefone;
    private javax.swing.JTextField i_data;
    private javax.swing.JTextField i_pprice;
    private javax.swing.JTextField i_pprice1;
    private javax.swing.JTextField i_pqnt1;
    private javax.swing.JTextField i_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tb_carrinho;
    private javax.swing.JTable tb_clientes;
    private javax.swing.JTable tb_products;
    // End of variables declaration//GEN-END:variables
}
